export interface Tool {
  id: string;
  name: string;
  category: string;
  description: string;
  pricing: string;
  pricingTier: "free" | "freemium" | "paid" | "enterprise";
  url: string;
  logo?: string;
  features: string[];
  pros: string[];
  cons: string[];
  bestFor: string;
  users?: number;
  rating?: number;
  yearFounded?: number;
}

export const tools: Tool[] = [
  {
    id: "vscode",
    name: "Visual Studio Code",
    category: "Code Editor",
    description: "Free, lightweight code editor with powerful features and massive extension ecosystem",
    pricing: "Free",
    pricingTier: "free",
    url: "https://code.visualstudio.com",
    features: ["IntelliSense", "Debugging", "Git Integration", "Extensions", "Remote Development", "Live Share"],
    pros: ["Lightweight", "Highly customizable", "Massive extension market", "Free", "Cross-platform"],
    cons: ["Can be slow with many extensions", "Requires configuration for some languages"],
    bestFor: "General-purpose development, web development, quick scripting",
    users: 15000000,
    rating: 4.8,
    yearFounded: 2015,
  },
  {
    id: "jetbrains-idea",
    name: "JetBrains IntelliJ IDEA",
    category: "Code Editor",
    description: "Powerful IDE for Java and JVM languages with intelligent code assistance",
    pricing: "$199/year (Community: Free)",
    pricingTier: "freemium",
    url: "https://www.jetbrains.com/idea",
    features: ["Smart Code Completion", "Refactoring", "Debugging", "Testing", "Version Control"],
    pros: ["Excellent Java support", "Smart refactoring", "Built-in tools", "Community edition free"],
    cons: ["Heavy resource usage", "Steep learning curve", "Paid license expensive"],
    bestFor: "Enterprise Java development, large projects",
    users: 5000000,
    rating: 4.7,
    yearFounded: 2000,
  },
  {
    id: "sublime-text",
    name: "Sublime Text",
    category: "Code Editor",
    description: "Lightweight, sophisticated text editor for code, markup and prose",
    pricing: "$99 (one-time)",
    pricingTier: "paid",
    url: "https://www.sublimetext.com",
    features: ["Multiple Selections", "Command Palette", "Goto Anything", "Split Editing", "Plugins"],
    pros: ["Very fast", "Minimal interface", "Powerful search", "One-time purchase"],
    cons: ["Limited built-in features", "Smaller community than VS Code", "Paid license"],
    bestFor: "Fast editing, minimalist workflow, experienced developers",
    users: 2000000,
    rating: 4.5,
    yearFounded: 2008,
  },
  {
    id: "github",
    name: "GitHub",
    category: "Version Control",
    description: "Web-based Git repository hosting with collaboration features",
    pricing: "Free (Pro: $4/month)",
    pricingTier: "freemium",
    url: "https://github.com",
    features: ["Git Hosting", "Pull Requests", "Issues", "Actions", "Pages", "Copilot"],
    pros: ["Largest developer community", "Excellent UI", "GitHub Actions CI/CD", "Free for public repos"],
    cons: ["Owned by Microsoft", "Limited on free tier", "Can be pricey at scale"],
    bestFor: "Open source projects, team collaboration, public repositories",
    users: 100000000,
    rating: 4.9,
    yearFounded: 2008,
  },
  {
    id: "gitlab",
    name: "GitLab",
    category: "Version Control",
    description: "Complete DevOps platform with built-in CI/CD and repository management",
    pricing: "Free (Premium: $29/month)",
    pricingTier: "freemium",
    url: "https://gitlab.com",
    features: ["Git Hosting", "CI/CD Pipeline", "Issue Tracking", "Wiki", "Container Registry", "Security"],
    pros: ["All-in-one platform", "Strong CI/CD", "Self-hosted option", "Good for enterprises"],
    cons: ["Steeper learning curve", "UI less intuitive than GitHub", "Smaller community"],
    bestFor: "Enterprise deployments, complex CI/CD pipelines, self-hosted solutions",
    users: 30000000,
    rating: 4.6,
    yearFounded: 2011,
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    category: "Version Control",
    description: "Git and Mercurial repository hosting integrated with Jira",
    pricing: "Free (Premium: $3-5/user/month)",
    pricingTier: "freemium",
    url: "https://bitbucket.org",
    features: ["Git Hosting", "Mercurial Support", "Jira Integration", "Pipelines", "Smart Mirroring"],
    pros: ["Jira integration", "Good for teams", "Mercurial support", "Free tier generous"],
    cons: ["Smaller community than GitHub", "Less popular for open source", "UI can be confusing"],
    bestFor: "Teams using Jira, Atlassian ecosystem, enterprise projects",
    users: 10000000,
    rating: 4.3,
    yearFounded: 2008,
  },
  {
    id: "docker",
    name: "Docker",
    category: "Containerization",
    description: "Containerization platform for packaging applications and dependencies",
    pricing: "Free (Pro: $5/month)",
    pricingTier: "freemium",
    url: "https://www.docker.com",
    features: ["Container Runtime", "Docker Compose", "Docker Hub", "BuildKit", "Desktop IDE"],
    pros: ["Industry standard", "Excellent documentation", "Large ecosystem", "Easy to learn"],
    cons: ["Resource intensive", "Learning curve for beginners", "Licensing complexity"],
    bestFor: "Microservices, deployment consistency, development environments",
    users: 50000000,
    rating: 4.8,
    yearFounded: 2013,
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    category: "Container Orchestration",
    description: "Open-source container orchestration platform for automating deployment",
    pricing: "Free (Managed services: varies)",
    pricingTier: "free",
    url: "https://kubernetes.io",
    features: ["Auto-scaling", "Self-healing", "Load Balancing", "Storage Orchestration", "Declarative Config"],
    pros: ["Industry standard", "Highly scalable", "Large community", "Open source"],
    cons: ["Steep learning curve", "Complex to set up", "Resource intensive", "Overkill for small projects"],
    bestFor: "Large-scale deployments, microservices, cloud-native applications",
    users: 10000000,
    rating: 4.7,
    yearFounded: 2014,
  },
  {
    id: "npm",
    name: "npm",
    category: "Package Manager",
    description: "JavaScript package manager and registry with 2+ million packages",
    pricing: "Free (Pro: $7/month)",
    pricingTier: "freemium",
    url: "https://www.npmjs.com",
    features: ["Package Registry", "CLI Tool", "Private Packages", "Organizations", "Audit"],
    pros: ["Largest package ecosystem", "Easy to use", "Built into Node.js", "Good security features"],
    cons: ["Dependency bloat", "Slow installs sometimes", "Quality varies across packages"],
    bestFor: "JavaScript/Node.js projects, web development",
    users: 20000000,
    rating: 4.6,
    yearFounded: 2010,
  },
  {
    id: "yarn",
    name: "Yarn",
    category: "Package Manager",
    description: "Fast, reliable, and secure JavaScript package manager",
    pricing: "Free",
    pricingTier: "free",
    url: "https://yarnpkg.com",
    features: ["Offline Mode", "Deterministic Installs", "Workspaces", "Plug'n'Play", "Security Audit"],
    pros: ["Fast and reliable", "Better dependency resolution", "Offline support", "Workspaces for monorepos"],
    cons: ["Smaller ecosystem than npm", "Steeper learning curve", "Less documentation"],
    bestFor: "Large monorepos, teams needing fast installs, JavaScript projects",
    users: 5000000,
    rating: 4.7,
    yearFounded: 2016,
  },
  {
    id: "pnpm",
    name: "pnpm",
    category: "Package Manager",
    description: "Fast, disk space efficient package manager with strict dependency resolution",
    pricing: "Free",
    pricingTier: "free",
    url: "https://pnpm.io",
    features: ["Monorepo Support", "Strict Dependency Resolution", "Disk Efficient", "Fast", "Workspaces"],
    pros: ["Fastest install times", "Disk space efficient", "Strict dependency management", "Great for monorepos"],
    cons: ["Newer, smaller community", "Less documentation", "Some package compatibility issues"],
    bestFor: "Monorepos, performance-critical projects, disk-space limited environments",
    users: 2000000,
    rating: 4.8,
    yearFounded: 2016,
  },
  {
    id: "react",
    name: "React",
    category: "Frontend Framework",
    description: "JavaScript library for building user interfaces with components",
    pricing: "Free",
    pricingTier: "free",
    url: "https://react.dev",
    features: ["Component-based", "Virtual DOM", "JSX", "Hooks", "Context API", "Ecosystem"],
    pros: ["Largest community", "Excellent documentation", "Flexible", "Great tooling"],
    cons: ["Steep learning curve", "JSX can be confusing", "Requires additional libraries"],
    bestFor: "Single-page applications, complex UIs, large teams",
    users: 15000000,
    rating: 4.9,
    yearFounded: 2013,
  },
  {
    id: "vue",
    name: "Vue.js",
    category: "Frontend Framework",
    description: "Progressive JavaScript framework for building user interfaces",
    pricing: "Free",
    pricingTier: "free",
    url: "https://vuejs.org",
    features: ["Reactive Data Binding", "Component System", "Single File Components", "Composition API", "Ecosystem"],
    pros: ["Easy to learn", "Excellent documentation", "Flexible", "Great developer experience"],
    cons: ["Smaller community than React", "Fewer job opportunities", "Fewer third-party libraries"],
    bestFor: "Rapid development, small to medium projects, developer happiness",
    users: 5000000,
    rating: 4.8,
    yearFounded: 2014,
  },
  {
    id: "angular",
    name: "Angular",
    category: "Frontend Framework",
    description: "Full-featured framework for building dynamic web applications",
    pricing: "Free",
    pricingTier: "free",
    url: "https://angular.io",
    features: ["TypeScript-first", "Dependency Injection", "RxJS", "CLI", "Testing Tools", "Routing"],
    pros: ["Full-featured", "Strong TypeScript support", "Great for large projects", "Enterprise-ready"],
    cons: ["Steep learning curve", "Verbose", "Overkill for small projects", "Smaller community than React"],
    bestFor: "Large enterprise applications, TypeScript projects, complex requirements",
    users: 3000000,
    rating: 4.5,
    yearFounded: 2010,
  },
  {
    id: "svelte",
    name: "Svelte",
    category: "Frontend Framework",
    description: "Compiler-based framework that builds highly efficient applications",
    pricing: "Free",
    pricingTier: "free",
    url: "https://svelte.dev",
    features: ["Compiler-based", "Reactive", "Scoped Styling", "Animations", "Stores", "SvelteKit"],
    pros: ["Smallest bundle sizes", "Excellent performance", "Easy to learn", "Less boilerplate"],
    cons: ["Smaller ecosystem", "Fewer job opportunities", "Less mature than React/Vue"],
    bestFor: "Performance-critical applications, small teams, learning frontend development",
    users: 1000000,
    rating: 4.8,
    yearFounded: 2016,
  },
  {
    id: "nextjs",
    name: "Next.js",
    category: "Meta Framework",
    description: "React framework with server-side rendering, static generation, and API routes",
    pricing: "Free (Vercel hosting: varies)",
    pricingTier: "free",
    url: "https://nextjs.org",
    features: ["SSR/SSG", "API Routes", "File-based Routing", "Image Optimization", "Middleware", "Deployment"],
    pros: ["Great developer experience", "Excellent performance", "Full-stack capabilities", "Easy deployment"],
    cons: ["Requires Node.js", "Steeper learning curve", "Vendor lock-in with Vercel"],
    bestFor: "Full-stack applications, SEO-critical sites, rapid development",
    users: 5000000,
    rating: 4.9,
    yearFounded: 2016,
  },
  {
    id: "nuxt",
    name: "Nuxt",
    category: "Meta Framework",
    description: "Vue framework for building universal applications with SSR and static generation",
    pricing: "Free (Vercel hosting: varies)",
    pricingTier: "free",
    url: "https://nuxt.com",
    features: ["SSR/SSG", "File-based Routing", "Auto-imports", "Modules", "Deployment", "API Routes"],
    pros: ["Easy to learn", "Great developer experience", "Vue ecosystem", "Good documentation"],
    cons: ["Smaller community than Next.js", "Fewer job opportunities", "Less mature ecosystem"],
    bestFor: "Vue-based full-stack applications, SEO-critical sites, rapid development",
    users: 1000000,
    rating: 4.7,
    yearFounded: 2016,
  },
  {
    id: "astro",
    name: "Astro",
    category: "Meta Framework",
    description: "Build fast websites with less JavaScript and support for multiple frameworks",
    pricing: "Free",
    pricingTier: "free",
    url: "https://astro.build",
    features: ["Zero JS by default", "Multi-framework", "Static Generation", "API Routes", "Content Collections"],
    pros: ["Fastest performance", "Less JavaScript", "Framework agnostic", "Great for content sites"],
    cons: ["Newer, smaller community", "Less documentation", "Limited dynamic capabilities"],
    bestFor: "Content-heavy sites, blogs, documentation, performance-critical applications",
    users: 500000,
    rating: 4.8,
    yearFounded: 2021,
  },
  {
    id: "python",
    name: "Python",
    category: "Programming Language",
    description: "Versatile, easy-to-learn programming language for web, data science, and automation",
    pricing: "Free",
    pricingTier: "free",
    url: "https://www.python.org",
    features: ["Simple Syntax", "Large Standard Library", "Extensive Packages", "Cross-platform", "REPL"],
    pros: ["Easy to learn", "Huge ecosystem", "Great for data science", "Versatile"],
    cons: ["Slower than compiled languages", "GIL limitations", "Mobile development limited"],
    bestFor: "Data science, machine learning, web development, automation, scripting",
    users: 50000000,
    rating: 4.9,
    yearFounded: 1991,
  },
  {
    id: "typescript",
    name: "TypeScript",
    category: "Programming Language",
    description: "Typed superset of JavaScript that compiles to plain JavaScript",
    pricing: "Free",
    pricingTier: "free",
    url: "https://www.typescriptlang.org",
    features: ["Static Typing", "Interfaces", "Generics", "Decorators", "Modules", "Tooling"],
    pros: ["Better IDE support", "Catches errors early", "Excellent documentation", "Growing adoption"],
    cons: ["Compilation step", "Learning curve", "Slower development initially", "Setup complexity"],
    bestFor: "Large projects, teams, type-safe development, modern JavaScript",
    users: 20000000,
    rating: 4.8,
    yearFounded: 2012,
  },
  {
    id: "rust",
    name: "Rust",
    category: "Programming Language",
    description: "Systems programming language focused on safety, speed, and concurrency",
    pricing: "Free",
    pricingTier: "free",
    url: "https://www.rust-lang.org",
    features: ["Memory Safety", "Concurrency", "Zero-cost Abstractions", "Pattern Matching", "Cargo"],
    pros: ["Memory safe", "Fast", "Great error messages", "Growing ecosystem"],
    cons: ["Steep learning curve", "Slower compilation", "Smaller ecosystem than C++", "Niche use cases"],
    bestFor: "Systems programming, performance-critical code, WebAssembly, CLI tools",
    users: 3000000,
    rating: 4.8,
    yearFounded: 2010,
  },
  {
    id: "go",
    name: "Go",
    category: "Programming Language",
    description: "Compiled language designed for simplicity, concurrency, and fast execution",
    pricing: "Free",
    pricingTier: "free",
    url: "https://golang.org",
    features: ["Concurrency", "Fast Compilation", "Static Typing", "Goroutines", "Standard Library"],
    pros: ["Simple syntax", "Fast compilation", "Great concurrency", "Easy deployment"],
    cons: ["Minimal standard library", "No generics (until 1.18)", "Smaller ecosystem", "Less suitable for complex UIs"],
    bestFor: "Backend services, DevOps tools, microservices, CLI applications",
    users: 5000000,
    rating: 4.7,
    yearFounded: 2009,
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    category: "Database",
    description: "Advanced open-source relational database with powerful features",
    pricing: "Free (Managed: varies)",
    pricingTier: "free",
    url: "https://www.postgresql.org",
    features: ["ACID Compliance", "JSON Support", "Full-text Search", "Replication", "Extensions", "Performance"],
    pros: ["Powerful features", "Reliable", "Great community", "Excellent documentation"],
    cons: ["Steeper learning curve", "More complex setup", "Slower than specialized databases for specific tasks"],
    bestFor: "Complex queries, relational data, enterprise applications, data warehouses",
    users: 10000000,
    rating: 4.9,
    yearFounded: 1996,
  },
  {
    id: "mongodb",
    name: "MongoDB",
    category: "Database",
    description: "NoSQL document database with flexible schema and horizontal scalability",
    pricing: "Free (Atlas: $0-1000+/month)",
    pricingTier: "freemium",
    url: "https://www.mongodb.com",
    features: ["Document Store", "Flexible Schema", "Horizontal Scaling", "Aggregation Pipeline", "Transactions"],
    pros: ["Flexible schema", "Easy to scale", "Developer-friendly", "Good for rapid development"],
    cons: ["Higher memory usage", "Less mature transactions", "Can lead to data inconsistency", "Licensing concerns"],
    bestFor: "Rapid prototyping, flexible data models, scalable applications, content management",
    users: 5000000,
    rating: 4.6,
    yearFounded: 2009,
  },
  {
    id: "redis",
    name: "Redis",
    category: "Database",
    description: "In-memory data structure store used for caching and real-time applications",
    pricing: "Free (Managed: $15-1000+/month)",
    pricingTier: "free",
    url: "https://redis.io",
    features: ["In-memory", "Data Structures", "Persistence", "Replication", "Pub/Sub", "Transactions"],
    pros: ["Extremely fast", "Simple to use", "Great for caching", "Excellent for real-time"],
    cons: ["Limited to available RAM", "Single-threaded", "Data loss on restart (without persistence)"],
    bestFor: "Caching, sessions, real-time features, message queues, leaderboards",
    users: 5000000,
    rating: 4.8,
    yearFounded: 2009,
  },
  {
    id: "graphql",
    name: "GraphQL",
    category: "API Query Language",
    description: "Query language and runtime for APIs with precise data fetching",
    pricing: "Free",
    pricingTier: "free",
    url: "https://graphql.org",
    features: ["Declarative Data Fetching", "Strong Typing", "Real-time Subscriptions", "Introspection", "Tooling"],
    pros: ["Precise data fetching", "Great developer experience", "Self-documenting", "Excellent tooling"],
    cons: ["Learning curve", "Caching complexity", "Overkill for simple APIs", "Query complexity attacks"],
    bestFor: "Complex data requirements, mobile applications, rapid frontend development",
    users: 3000000,
    rating: 4.7,
    yearFounded: 2015,
  },
  {
    id: "rest",
    name: "REST",
    category: "API Architecture",
    description: "Architectural style for designing networked applications using HTTP",
    pricing: "Free",
    pricingTier: "free",
    url: "https://restfulapi.net",
    features: ["Stateless", "Cacheable", "Client-Server", "Uniform Interface", "Layered System"],
    pros: ["Simple to understand", "Standard HTTP methods", "Great caching", "Widely adopted"],
    cons: ["Over-fetching/under-fetching", "Multiple requests needed", "Versioning challenges"],
    bestFor: "Simple to moderate APIs, public APIs, traditional web services",
    users: 50000000,
    rating: 4.7,
    yearFounded: 2000,
  },
  {
    id: "tailwindcss",
    name: "Tailwind CSS",
    category: "CSS Framework",
    description: "Utility-first CSS framework for rapidly building custom designs",
    pricing: "Free",
    pricingTier: "free",
    url: "https://tailwindcss.com",
    features: ["Utility Classes", "Responsive Design", "Dark Mode", "Customization", "Plugins", "JIT Compiler"],
    pros: ["Rapid development", "Highly customizable", "Small bundle sizes", "Great community"],
    cons: ["Learning curve", "HTML bloat", "Different mindset from traditional CSS", "Requires build step"],
    bestFor: "Rapid UI development, custom designs, responsive applications",
    users: 5000000,
    rating: 4.8,
    yearFounded: 2017,
  },
  {
    id: "bootstrap",
    name: "Bootstrap",
    category: "CSS Framework",
    description: "Popular CSS framework for building responsive and mobile-first websites",
    pricing: "Free",
    pricingTier: "free",
    url: "https://getbootstrap.com",
    features: ["Pre-built Components", "Responsive Grid", "Utilities", "Customization", "Documentation"],
    pros: ["Easy to learn", "Great documentation", "Pre-built components", "Large community"],
    cons: ["Generic look", "Larger bundle sizes", "Less customizable than Tailwind", "Opinionated"],
    bestFor: "Rapid prototyping, beginners, projects needing quick UI setup",
    users: 10000000,
    rating: 4.5,
    yearFounded: 2011,
  },
  {
    id: "jest",
    name: "Jest",
    category: "Testing Framework",
    description: "JavaScript testing framework with zero configuration and great documentation",
    pricing: "Free",
    pricingTier: "free",
    url: "https://jestjs.io",
    features: ["Zero Config", "Snapshot Testing", "Code Coverage", "Mocking", "Watch Mode", "Parallel Testing"],
    pros: ["Easy to set up", "Great documentation", "Fast", "Comprehensive"],
    cons: ["Can be slow for large test suites", "Snapshot testing can be problematic", "Memory intensive"],
    bestFor: "JavaScript/React testing, unit tests, integration tests",
    users: 5000000,
    rating: 4.8,
    yearFounded: 2014,
  },
  {
    id: "vitest",
    name: "Vitest",
    category: "Testing Framework",
    description: "Unit testing framework powered by Vite with Jest-compatible API",
    pricing: "Free",
    pricingTier: "free",
    url: "https://vitest.dev",
    features: ["Vite-powered", "Jest Compatible", "Fast", "Smart Watch Mode", "Coverage", "Parallel Testing"],
    pros: ["Very fast", "Jest compatible", "Great developer experience", "Modern tooling"],
    cons: ["Newer, smaller community", "Less documentation than Jest", "Fewer plugins"],
    bestFor: "Modern JavaScript projects, Vite-based applications, performance-critical testing",
    users: 1000000,
    rating: 4.8,
    yearFounded: 2021,
  },
  {
    id: "github-actions",
    name: "GitHub Actions",
    category: "CI/CD",
    description: "Workflow automation platform built into GitHub for CI/CD",
    pricing: "Free (2000 minutes/month)",
    pricingTier: "free",
    url: "https://github.com/features/actions",
    features: ["Workflow Automation", "Matrix Builds", "Caching", "Artifacts", "Secrets", "Marketplace"],
    pros: ["Integrated with GitHub", "Free tier generous", "Easy to set up", "Great community"],
    cons: ["Limited to GitHub", "Can be expensive at scale", "Slower than some alternatives"],
    bestFor: "GitHub projects, open source, continuous integration and deployment",
    users: 10000000,
    rating: 4.7,
    yearFounded: 2019,
  },
  {
    id: "circleci",
    name: "CircleCI",
    category: "CI/CD",
    description: "Modern CI/CD platform with powerful automation and integrations",
    pricing: "Free (limited, Pro: $15-75/month)",
    pricingTier: "freemium",
    url: "https://circleci.com",
    features: ["Workflows", "Orbs", "Caching", "Parallelization", "Insights", "Integrations"],
    pros: ["Fast builds", "Great documentation", "Powerful workflows", "Good free tier"],
    cons: ["Can be expensive", "Smaller community than GitHub Actions", "Setup complexity"],
    bestFor: "Complex CI/CD pipelines, enterprise projects, multi-repository workflows",
    users: 2000000,
    rating: 4.6,
    yearFounded: 2011,
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "Deployment",
    description: "Cloud platform optimized for frontend frameworks and serverless functions",
    pricing: "Free (Pro: $20/month)",
    pricingTier: "freemium",
    url: "https://vercel.com",
    features: ["Edge Functions", "Serverless Functions", "Analytics", "Monitoring", "Git Integration", "Deployment"],
    pros: ["Excellent for Next.js", "Great performance", "Easy deployment", "Good free tier"],
    cons: ["Vendor lock-in", "Can be expensive", "Limited backend capabilities"],
    bestFor: "Next.js applications, frontend projects, serverless functions",
    users: 2000000,
    rating: 4.8,
    yearFounded: 2015,
  },
  {
    id: "netlify",
    name: "Netlify",
    category: "Deployment",
    description: "Platform for building, deploying, and scaling web applications",
    pricing: "Free (Pro: $19/month)",
    pricingTier: "freemium",
    url: "https://www.netlify.com",
    features: ["Git Integration", "Serverless Functions", "Forms", "Analytics", "Edge Functions", "Deployment"],
    pros: ["Easy to use", "Great for static sites", "Good free tier", "Excellent documentation"],
    cons: ["Can be expensive", "Limited backend capabilities", "Smaller ecosystem than Vercel"],
    bestFor: "Static sites, JAMstack applications, serverless functions",
    users: 1000000,
    rating: 4.7,
    yearFounded: 2014,
  },
  {
    id: "aws",
    name: "AWS",
    category: "Cloud Platform",
    description: "Comprehensive cloud computing platform with 200+ services",
    pricing: "Free tier + pay-as-you-go",
    pricingTier: "freemium",
    url: "https://aws.amazon.com",
    features: ["EC2", "S3", "Lambda", "RDS", "CloudFront", "100+ more services"],
    pros: ["Most comprehensive", "Largest market share", "Excellent documentation", "Enterprise support"],
    cons: ["Steep learning curve", "Complex pricing", "Overkill for small projects", "Steep learning curve"],
    bestFor: "Enterprise applications, complex architectures, large-scale projects",
    users: 10000000,
    rating: 4.7,
    yearFounded: 2006,
  },
];

export const categories = [
  "Code Editor",
  "Version Control",
  "Containerization",
  "Container Orchestration",
  "Package Manager",
  "Frontend Framework",
  "Meta Framework",
  "Programming Language",
  "Database",
  "API Query Language",
  "API Architecture",
  "CSS Framework",
  "Testing Framework",
  "CI/CD",
  "Deployment",
  "Cloud Platform",
];

export function getToolById(id: string): Tool | undefined {
  return tools.find((tool) => tool.id === id);
}

export function getToolsByCategory(category: string): Tool[] {
  return tools.filter((tool) => tool.category === category);
}

export function searchTools(query: string): Tool[] {
  const lowerQuery = query.toLowerCase();
  return tools.filter(
    (tool) =>
      tool.name.toLowerCase().includes(lowerQuery) ||
      tool.description.toLowerCase().includes(lowerQuery) ||
      tool.category.toLowerCase().includes(lowerQuery)
  );
}
